FROM node:14.15.5-slim As builder
WORKDIR /app
COPY BackEnd/JeeAccount/package.json ./
COPY BackEnd/JeeAccount/dps-lib-3.1.11.tgz ./
RUN yarn install
COPY BackEnd/JeeAccount /app/
RUN yarn build_stage

FROM nginx:1.19.8-alpine
COPY backend.nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/ /usr/share/nginx/html
EXPOSE 80