export const environment = {
  production: true,
  appVersion: 'v717demo1',
  USERDATA_KEY: 'authf649fc9a5f55',
  isMockEnabled: true,
  apiUrl: 'api',
  APPCODE: 'ACCOUNT',
  APPCODE_JEEHR: 'JeeHR',
  APPCODE_LANDING: 'LANDING',
  APPCONFIG_SSO: 'sso_token',
  HOST_SOCKET: 'wss://socket.jee.vn',
  HOST_JEEACCOUNT_API: 'https://jeeaccount-api.jee.vn',
  HOST_IDENTITYSERVER_API: 'https://identityserver.jee.vn',
  HOST_PORTAL_API: 'https://portal.jee.vn',
  HOST_JEECOMMENT_API: 'https://jeecomment-api.jee.vn',
  HOST_JEELANDINGPAGE_API: 'https://jeeglobal-api.jee.vn',
  HOST_JEELANDINGPAGE: 'https://app.jee.vn',
  HOST_JEECHAT_API: 'https://jeechat-api.jee.vn',
  HOST_JEECHAT: 'https://jeechat.jee.vn',
  //notification
  HOST_WEBSOCKET: 'wss://socket.jee.vn',
  HOST_NOTIFICATION: 'https://notification.jee.vn',
  DOMAIN_COOKIES: '.jee.vn',
};
