version: '3.9'

networks:
  vault_vault_network:
    external: true
  traefik_traefik-network:
    external: true
  kafka-network:
    external: true

services:
  api:
    image: registry.jee.vn/hoaaq/jeeaccount-api:latest
    networks:
      - vault_vault_network
      - traefik_traefik-network
      - kafka-network
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      KafkaConfig__Brokers: ${KAFKA_BROKER}
      KafkaConfig__ProjectName: jee-account
      VaultConfig__Endpoint: ${VAULT_ENDPOINT}
      VaultConfig__Token: ${VAULT_TOKEN}
      JeeAccount__API: ${PUBLIC_LINK_API}
      ConnectionStrings__DefaultConnection: ${CONNECTION_STRING}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_traefik-network
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.jeeaccountapi-http.rule=Host(`jeeaccount-api.${DOMAIN}`)
        - traefik.http.routers.jeeaccountapi-http.entrypoints=http
        - traefik.http.routers.jeeaccountapi-http.middlewares=https-redirect
        - traefik.http.routers.jeeaccountapi-https.rule=Host(`jeeaccount-api.${DOMAIN}`)
        - traefik.http.routers.jeeaccountapi-https.entrypoints=https
        - traefik.http.routers.jeeaccountapi-https.tls=true
        - traefik.http.routers.jeeaccountapi-https.tls.certresolver=le
        - traefik.http.services.jeeaccountapi.loadbalancer.server.port=80

  backend:
    image: registry.jee.vn/hoaaq/jeeaccount-backend:latest
    networks:
      - traefik_traefik-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_traefik-network
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.jeeaccountbackend-http.rule=Host(`jeeaccount.${DOMAIN}`)
        - traefik.http.routers.jeeaccountbackend-http.entrypoints=http
        - traefik.http.routers.jeeaccountbackend-http.middlewares=https-redirect
        - traefik.http.routers.jeeaccountbackend-https.rule=Host(`jeeaccount.${DOMAIN}`)
        - traefik.http.routers.jeeaccountbackend-https.entrypoints=https
        - traefik.http.routers.jeeaccountbackend-https.tls=true
        - traefik.http.routers.jeeaccountbackend-https.tls.certresolver=le
        - traefik.http.services.jeeaccountbackend.loadbalancer.server.port=80